/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BlurText: typeof import('./src/components/bits/BlurText.vue')['default']
    Button: typeof import('./src/components/ui/Button.vue')['default']
    Card: typeof import('./src/components/ui/Card.vue')['default']
    ContentModal: typeof import('./src/components/modals/ContentModal.vue')['default']
    GlassMessage: typeof import('./src/components/ui/GlassMessage.vue')['default']
    IconButton: typeof import('./src/components/ui/IconButton.vue')['default']
    Info: typeof import('./src/components/ui/Info.vue')['default']
    Input: typeof import('./src/components/ui/Input.vue')['default']
    Modal: typeof import('./src/components/ui/Modal.vue')['default']
    MouseEffect: typeof import('./src/components/effects/MouseEffect.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/layout/SideBar.vue')['default']
    SplitText: typeof import('./src/components/bits/SplitText.vue')['default']
    Switch: typeof import('./src/components/ui/Switch.vue')['default']
    Tabs: typeof import('./src/components/ui/Tabs.vue')['default']
    TitleBar: typeof import('./src/components/layout/TitleBar.vue')['default']
  }
}
